### ISSUE TITLE
Environment Setup Issues - Requesting Details on the Development Environment

### ISSUE THREAD

**Issue by Yatogaii** [icra-team/icra#3]
Hello,

Thank you for making your tool available as open-source. I’m currently trying to replicate the results of your paper using the provided repository, but I’m encountering several issues related to OCaml, SCons, and other dependencies.

Could you please provide details on the exact environment (OS, specific versions of dependencies like OCaml, SCons, etc.) that you used to successfully build and run the tool? Any guidance on resolving these issues would be greatly appreciated.

Thank you for your help!

**Comment by jbreck** [comment]
Hi!

For most (maybe all?) of the papers that we wrote on ICRA and related analysis tools, we included an artifact along with the paper; each artifact is a virtual machine that contains the analysis tool and a script that re-runs the tool to reproduce the paper's results.  (To find the VM, go to the web page for whichever paper you're interested in and look for the words "Supplementary Material" or "Related Artifact".  If you're having trouble finding it, just tell me which paper you're interested in, and I may be able to offer more guidance.)  Depending on your needs, you may be able to just use the VM to directly run whatever experiments you're interested in.  Alternatively, if you want to get the tool running outside of the VM, I suggest that you start by obtaining the VM, and from there, you can look up which versions the VM is using for all of the dependencies and build tools and stuff.

 - Jason

**Comment by Yatogaii** [comment]
Thank you for your quick response!

I've found the environment you provided integrated within the virtual machine. I’ll give it a try and see how it goes. I really appreciate your help and the detailed setup you’ve shared.

I’ll let you know if I encounter any further issues, but for now, this seems like a great solution.

Thanks again!

Best regards,
ykh
