### ISSUE TITLE
Unexpected Assertion Failure in Test Case on `icra_submission` Version

### ISSUE THREAD

**Issue by Yatogaii** [icra-team/icra#4]
Hello,

Thanks for your work!

Recently, I encountered an issue while testing the `icra_submission` version. In the following test case:

```c
#include <assert.h>
void start(int n, int m)
{
  int va=n;
  int vb=0;

  while (va > 0) {
    if (vb < m) {
      vb=vb+1;
      va=va-1;
    } else {
      vb=vb-1;
      vb=0;
    }
  }
  __VERIFIER_assert(va == 0);
  __VERIFIER_assert(vb == 10);
}

int main(){
    int n = 50;
    int m = 10;
    start(n, m);
    return 0;
}
```

The real output of the program when n=50,m=10 is va=0,vb=10.

But when i run `./icra.sh test.c`, the second assertion consistently fails with the error message:
`Assertion on line 18 FAILED`

**This occurs regardless of whether I use `assert(vb == 10)` or `assert(vb != 10)`.**

Could you please let me know if this behavior is expected? Or is there something wrong with how I'm using the code?

Thank you again for your hard work and for any guidance you can provide!

**Comment by jbreck** [comment]
Hello!

Here are a couple of thoughts off the top of my head:

1: In your code listing, the else branch contains two different assignments to "vb".  Is that a typo?

2: The meaning that we intend to convey by the message "assertion failed" is not that the asserted condition was proved to be false on some execution; it just means that ICRA could not prove that the asserted condition is true on every execution.  Given that interpretation, it's sound for ICRA to say that any assertion has failed.  It is a safe default message when ICRA's analysis is not precise enough.

 - Jason

**Comment by Yatogaii** [comment]
Thank you for the response!

1. The code is from the c4b test suite, specifically the `SPEED PLDI'09 fig4_2` case. I recently noticed that the original case (https://www.cs.yale.edu/homes/qcar/aaa/) is slightly different from the one you used in your tests (https://github.com/icra-team/icra/blob/master/WALi-OpenNWA/Examples/cprover/tests/c4b/speed_pldi09_fig4_2.c). It seems the original case included a redundant statement.

2. I think I understand your point. I also tested the bounds of vb and found the result to be `0 <= vb <= 103`. Since ICRA is a static analysis method based on a combination of symbolic analysis and abstract interpretation, which means the interval obtained is a superset of the concrete semantics. Values outside the interval can be definitively determined, but values within it might not be accurate. This can clear up our confusion, an assertion false doesn't absolutely indicate that the assertion is false; it might mean the assertion cannot be determined. 

Am I understanding correctly?

**Comment by jbreck** [comment]
1: Ah, right.  I very vaguely remember this program now.  Yes, we got this from the C4B materials, where it has that redundant statement.  That's pretty weird.  It even has the redundant statement in their tech report ([see page 23, Fig. 21, leftmost program, labeled fig4_2 here](https://www.cs.yale.edu/homes/qcar/aaa/data/amortimp15_tr.pdf)).  I guess the C4B authors ultimately got it from the PLDI'09 paper on SPEED ([see Fig 4, example 2 here](https://www.microsoft.com/en-us/research/wp-content/uploads/2009/03/pldi09_speed.pdf)) at which point it didn't have the redundant statement, and had slightly different variable names.

2: Yes, your understanding is correct.

**Comment by Yatogaii** [comment]
Thanks for taking the time, it really helps!
:)
